### ISSUE TITLE
Starfield

### ISSUE THREAD

**Issue by OleSchool60** [DaniAsh551/wemod-launcher#10]
Starfield will not run in GE-Proton7-35. The install of Wemod was installed with no problems. Is there a workaround to get Starfield to run?

**Comment by DaniAsh551** [comment]
After you get WeMod setup properly, you can try and change the Proton version.

Some versions may still break the WeMod setup and you would need to redo the setup from scratch.

**Comment by OleSchool60** [comment]
Thank you for your quick response. I'll give it a try.
________________________________

**Comment by OleSchool60** [comment]
When you change GE-Proton7-35 to any GE-Proton-8 which Starfield will run in. It breaks .Net. Is this a lost or is there any other way I can get it to run?
________________________________

**Comment by DaniAsh551** [comment]
I doubt our current approach to WeMod would work with Wine/Proton 8 and above, because some substantial changes (mostly PE conversion - I suppose). You could try with Wine/Proton 7.X or 6.X versions and see if you have any luck.

Unless we get some official help from WeMod, I am afraid the situation may not change - I am just a guy who doesn't use WeMod nor have a Steam Deck.

So, try asking WeMod for some form of official help, or if you have the know how, please open a PR when you find a method which works with Wine/Proton 8+. I would keep doing the same when I have some time. :)

**Comment by OleSchool60** [comment]
I want to thank you for taking a look at this. I figured as much with Proton8 not working with Wemod.

Thanks again
________________________________
