### ISSUE TITLE
[BUG/REGRESSION]: Regression in commit 0fa1fe2.

### ISSUE THREAD

**Issue by shymega** [DaniAsh551/wemod-launcher#104]
### Describe the bug

Whilst testing to resolve #100, I pulled the latest changes, to find the commit 0fa1fe2 had a regression.

Essentially, it's a type mismatch. I'm refactoring currently on my branch, and very alarmed to find the self-updater downloads from `main`. My suggested approach would be to develop in a `develop` branch, invite users to test, _then_ merge into `main`.

The launcher pulling without testing from `main` breaks the app too often, as well as leading to a degraded user experience.

Anyway, I'll discuss that with you in a separate tracking issue.

Thanks.

### Steps to reproduce the behavior

1. Launch Doom (2016), setup with Proton 9.1
2. Encounter type mismatch exception.

### Expected behavior

Doesn't work on NixOS yet, but I do expect this to happen with every distro currently.

### Logs

```shell
The wemod script wemod-laucher is running on version 1.484
The wemod script wemod-laucher is running on version 1.486

ERROR: ld.so: object '/home/dzr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Traceback (most recent call last):
  File "/home/dzr/Games/wemod-launcher-prod/wemod", line 68, in <module>
    python_venv = self_update(python_venv)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dzr/Games/wemod-launcher-prod/setup.py", line 249, in self_update
    if (upd and upd.lower() == "false") or infinite > 2:
                                           ^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
```

### System Information

OS: NixOS 24.05.
Proton: GE-9.1

**Comment by marvin1099** [comment]
While i do agree I'm just one guy.
I just really enjoy programming, open source and that others use what i make.
Whats the point I'm making you might ask, well i don't really use wemod
and if i really had a traditional dev branch where i only push from on major releases,
probably nobody except me would test the wemod code,
that means more work for me,
i already put a lot of work into this project and don't want to increase the work for me.
I also feel like the wemod-launcher is mostly feature complete.
Well maybe that to positive but as long as i don't have more help on this project,
auto merging will stay since it reduces my workload.
We can of course use a better CI system that can also find errors like these, it that exists.

**Comment by marvin1099** [comment]
Also if i was not clear we have a development branch named dev, and it auto merges to main it the ci system says this are ok, therfore we want to merge new things to dev, this will do a basic check and oly if it worked will the changes be pushed to main, so please send future fixes to dev, if i make a bigger feature i also create a seperate branch sometimes like i have done for the flatpak update, but i usualy dont do this for smal fixes.
