### ISSUE TITLE
The game does not respond to button presses

### ISSUE THREAD

**Issue by Dernogard** [DaniAsh551/wemod-launcher#117]
### Question

Hello. I tried to install it on my SteamDeck according to the instructions in the Discord. But every time it hung up at the dotnet48 download stage.  Then I tried not "build" but "download" and the proton 8+ version. Success, everything worked, and wemod launches the game. Inside wemod, I can select the game and "playing" it. But neither before nor after pressing this button, the game does not respond to button presses in any way. Feels like wemod (?) intercepts clicks without giving them to the game. 

### Environment Details

GE-Proton8-32
SteamDeck Oled (I dunno linux version)
last version of your script at the moment )

**Comment by marvin1099** [comment]
Is the discord still active?
If so how did you find that?
After setting the wemod mods in a way you want to have them, 
close the wemod window it will keep running in the background, 
that way wemod should not take any keybord inputs.
You can reopen wemod from the system tray.
if the issue is still there try without wemod,
if that still wont work the game is broken,
it may also be a issue with wemod itself not wemod-launcher,
keep in mind all that wemod-launcher is doing is installing and running,
the offical wemod under wine on linux.
Than means if this is a wemod or a game issue i can't help you.

**Comment by marvin1099** [comment]
I assume this was solved, if not say so and i will reopen this.
