### ISSUE TITLE
[BUG]: The WeMod launcher hangs my system after using any cheat once.

### ISSUE THREAD

**Issue by n3tis** [DaniAsh551/wemod-launcher#121]
### Describe the problem

WeMod starts successfully with not many issues aside from the window being somewhat sluggish (stuttery animations, slow responsiveness, etc). It also successfully detects the game and hooks to it after I point the executables location to it. Everything works but after using any cheat, even after disabling it, the game I'm playing (Project Wingman) hangs a few seconds after and entirely stops working. I had to restart my system until I found out I can use the SysRq key to terminate the process when it starts hanging my system.

### Steps that will result in the problem

1. Start Game using Lutris.
2. Play Campaign or Conquest. Regardless of whether or not you are "in the game", pressing a cheat will hang the game after a few seconds.
3. System freezes.

### Expected results

The cheat to work. And it does - but then it fails horrendously.

### Logs

[wemod.log](https://github.com/user-attachments/files/16871413/wemod.log)
Seems like there are also some errors from previous sessions made by the logger.

### System Information

Bazzite 40 (from Fedora Kinoite).
Intel(R) Core(TM) i7-4770 (8) @ 3,90 GHz
AMD Radeon RX 550 / 550 Series
16gb RAM
(game and wemod are both installed on a 256gb SSD)
1920x1080 screen - game ran at 1600x800
KDE Plasma 6.1.4
KWin (Wayland)

### Additional context

Version of the game is GOG, latest.

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by marvin1099** [comment]
Keep in mind the WeMod is actually a Windows program, so we can't actually change how WeMod works. 
Therefore, the stuff like bad animations are out of our hands
and the fact that the wemod-launcher crashes your PC is also out of our hands. 
According to the wemod.log the wemod-launcher is perfectly doing its intended job.

You can try to use it without Wayland, which is known to cause issues with WeMod.
You can also try with a different proton version, which also sometimes solves the issue.
GE-Proton9.8 was last tested, but any GE-Proton9 version should work fine.
If you tried clicking on the mod to activate, you can also try the hotkey or 
the other way around so click instead of the hotkey, that only works for some mods though.
You can try to delete the game prefix and recreate it to see if that works.

For a bit of context, all that the wemod-launcher is doing is installing some software, 
to make WeMod run under Wine and then starting WeMod with the game. 
It really just installs the same software you need on Windows to run WeMod like .NET.

**Comment by n3tis** [comment]
I'm not sure how to run it in another way instead of Wayland.
I used hotkeys.

**Comment by marvin1099** [comment]
> I'm not sure how to run it in another way instead of Wayland. I used hotkeys.

Try kicking to activate the mods.
Also try x11 instead of Wayland.

**Comment by marvin1099** [comment]
I assume this has answered the question.
So i will close this, if this is not the case say so.

**Comment by n3tis** [comment]
> > I'm not sure how to run it in another way instead of Wayland. I used hotkeys.
> 
> Try kicking to activate the mods. Also try x11 instead of Wayland.

I haven't had made any attempts cause I was too busy. Again, I don't really know how to kick or how to use X11 instead of Wayland, considering I am mostly an amateur linux user.

**Comment by marvin1099** [comment]
To try it with x11 instead, I'm not 100% shure myself.
Your distro may have x11 installed in that case click on logout instead of shutdown or reboot.
After that you should be greated by a login screen,
down at the bottom left (might be in a other place on the screen) there will be a selection to switch between x11 and Wayland.
This selection will just look like a button that says Wayland until you click it.
After you click it the selection will show up.
If this is not there it might be possible that your distro is missing x11 by default.
In that case you will need to install it.
To do that google "MYDISTRO install DESKTOP wayland", my distro will be your distro listed in system information and desktop will be your desktop listed in system information (most likely this will be KDE plasma or GNOME).
You may also be able to install xwayland and run the game and launcher over that.
But I have ni idea his to do that.
To make that work I recomend you google "Force run apps under Wayland with xwayland".
You can also use something like:
https://chatgpt.com/ or https://huggingface.co/chat/
These are awnsering maschines, they will basic awnser any question you may have.
But they are like humans, sometimes they will be shure they have the right awnser but they wont, so dobble check important information online.
Sometimes more info can also help these awnsering Maschines give better awnsers.
You can also ask something like make your awnser shorter or give your opinion to xxxx.
