### ISSUE TITLE
[Question] How to use it with a argument?

### ISSUE THREAD

**Issue by mzigaib** [DaniAsh551/wemod-launcher#127]
### Question

I am trying to run a game on Steam with the argument ´Steamdeck=1 %command´, I tried several options like ´/home/$USER/wemod-launcher Steamdeck=1 %command´ but it did not work, how can I do that?
Thanks!

### Environment Details

Steamdeck=1

**Comment by marvin1099** [comment]
%command% will be replaced by the command to start the game (steam will do this automatically),
it may look like this:
proton -run game.exe
this is not realy how this looks but it helps to expain arguments.
What you are doing is allmost like setting a environment variable.
That works like this:
WINELOG=text.txt /home/$USER/wemod-launcher %command%
Now you want to send a argument that is a bit different it may look like this:
 /home/$USER/wemod-launcher %command% --myargument

May times arguments just look like this:
--WORD
Sometimes its like this:
--SETTING=1
Sometimes the -- may not be needed.

So i suggest trying one of these:
```
/home/$USER/wemod-launcher %command% Steamdeck=1
/home/$USER/wemod-launcher %command% Steamdeck
/home/$USER/wemod-launcher %command% --Steamdeck=1
/home/$USER/wemod-launcher %command% --Steamdeck
```

Or if this is a environment variable then try:
```
Steamdeck=1 /home/$USER/wemod-launcher %command%
```

Lastly as info argumens get send to a app ,
so that means arguments are at the end of the app you want to send it too.
Like this `game.exe --coolsetting`
Since %command% gets replaced by the game command the game file will be at the end,
so the argument is also at the end.

Please report if this has worked, for you or have other questions.

**Comment by mzigaib** [comment]
Thank you very much for the explanation, I will try that see what happens

**Comment by mzigaib** [comment]
Sorry, none of the options seems to work, it seems that the "SteamDeck=1" is a environment variable and it does not seem to go through if you put after the %command% so Wemod starts but the game crashes as if there is no env set.

**Comment by marvin1099** [comment]
Good to hear, if you have other questions just ask, for now i will close this conversation
