### ISSUE TITLE
Games not working with "GE-Proton7-35"

### ISSUE THREAD

**Issue by pmmichalowski** [DaniAsh551/wemod-launcher#18]
Hi Some games don't work with "GE-Proton7-35" (Baldur's gate 3) do you plan to update the tool to newer version.

Also Great work, thank you!

**Comment by DaniAsh551** [comment]
Hi @pmmichalowski this issue was known from day one and yet, we are unable to make WeMod work with any more recent versions of proton.

But this is only true for when you setup the game with WeMod, you can switch proton versions after that and check whether your games work there.

Some people have reported that GE7-55 also works. If you find any other versions which work, you are welcome to let me know.
