### ISSUE TITLE
Issues on Steam Deck

### ISSUE THREAD

**Issue by cmsj** [DaniAsh551/wemod-launcher#2]
Hi!

I'm trying out the feat/automated branch on a Steam Deck and while I can get all the way through the installation, I've been unable to successfully get WeMod to launch - it always gives me one of two errors while it's starting.

I was chatting with Brandon (u/milkdude94 on Reddit) and he gave me some pointers that got me this far, but I'm clearly still doing something wrong.

I've documented the exact things I did here: https://docs.google.com/document/d/1DfjlN8EUvDG2dpUTuk-ILu3MrAyZrUf2z_RIA1byjK8/edit# 

I'd love to help out with getting the branch finished, and while my Python's fairly good, I know very little about wine/proton.

**Comment by cmsj** [comment]
(I also wonder if you might be on a Discord somewhere?)

**Comment by DaniAsh551** [comment]
Hi @cmsj ,

I just managed to take a look at what you had detailed in the document you shared and here are a few points:

* 4.b isn't needed as you suspected, wemod-launcher should grab and use the latest version by default
* STL is (ideally) not required, as wemod-launcher should take care of both the initial installation, prefix setup and launching the game with WeMod

But you can see the problem here, we aren't successful with the third step yet, with GE-Proton-3X wemod-launcher fails to setup the prefix because winetricks fails to install dotnet48 (which attempts to install other the previous versions of dotnet as well - at this stage, dotnet40 install fails and the whole operation is abandoned)

Having said that, according to milkdude94, installing just the dotnet48 manually is enough (I cannot replicate the success on my fedora machine though, but I have had some success on junest)


All in all, the way forward looks like this:
* Forget about installing dotnet48 with winetricks and make wemod-launcher do it
* Or alternatively, give the user two options, one to use winetricks and one to not use winetricks

This is a fairly simple fix really, but I haven't had much free time in the past few weeks, so if you are up to it, you are more than welcome to open a PR

**Comment by DeckyDoofus** [comment]
Hello, I've been trying to setup the launcher for 3 days now and i'm pretty sure i'm going insane, so ill start at the... start.. of my smooth-brain problems
_(i'm using the main/default branch)_ 
**THE PROBLEMS**
1
first of all, I don't think that 'GE-Proton-3x' can be downloaded on protonup- QT, and I can't find any reference to it online, maybe i'm stupid- or maybe you meant something else, but I cant find this version anywhere- not even in the official releases glorious eggroll has themselves, 

2
 next-  (sorry, there's more.) -I have no idea what I need to do to my launch options, do I need to copy the example? do I find the actual location of my wemod file and shove %command% after it? (i have tried both)    
 whatever I did it wont work, or even launch, maybe because of the wrong version of proton- it says loading for 5 seconds on the steam play button and then it stops and changes back to play, not even an error message
 
**Here's what I did for the launch options:**
i 'found the path to my wemod file which I assume means the location of it in my 'net45' folder from the WeMod download / install / unpack, or the one I copied in the wemod launcher folder I downloaded, I tried putting the path to both of these files followed by %command%, and we get a handy ol' nothing.
I tried the example you had on the instructions, and nothing.

for reference, here are the launch options I tried- as you'll see, i have wemod installed to my documents, and am very probably doing something wrong:

- /home/deck/Documents/net45/wemod %command%
- /home/deck/Documents/wemod-launcher-main/wemod %command%
- ENABLE_VKBASALT=1 WINE_FULLSCREEN_FSR=1 DXVK_ASYNC=1 PROTON_NO_ESYNC=1 DXVK_HUD=fps gamemoderun /home/user/WeMod/WeMod.sh %command% +com_showLoadingScreen 0 +r_skipDOF 1

**THE END OF IT**

I'm going to end this by saying a few things,
 thing 1: I'm new to linux and I'm sorry you have to explain things that could be simple for you, 
thing 2: I. Know. Nothing. I just want to have extra fun on the go with my steam deck.
thing 3: thanks, for taking the time and effort to make this, it's a godsend- and if you can help me fix my stupid mistakes I'll be flippin' ecstatic.

**Comment by DaniAsh551** [comment]
Hi @DeckyDoofus ,

I saw the notification for your post here a couple days ago, but I haven't really had the time to even take a look. I am traveling right now and would be for a considerable time still, so sorry for this late reply (and any that might come after - lol )

There are some known issues with the launcher right now, and a solid fix is yet to be pushed out, but the community does have some awesome workarounds.

Your last option (minus the ".sh" part), should work with the "feat/automated" branch, be sure to delete your prefix if you have made any modifications, and use GE-Proton-35 (this is what I mean by GE-Proton-3X).

In the meantime, I refer you to the community on discord, there should be someone who always helps even if I am unavailable most of the time:

https://discord.gg/5CXSakAv

**Comment by DeckyDoofus** [comment]
Thank you so much!

**Comment by Linrox** [comment]
I tried wemod on linux but the issue i ran into was even if it loads and starts a game, it says the is no licence for the game, and ghosts out all options except exit.
The game i tried was for COH.

**Comment by DaniAsh551** [comment]
@Linrox I have not yet faced this issue - which version of wemod are you using?

**Comment by DaniAsh551** [comment]
@Linrox this may be a new feature in the more recent versions of WeMod, so it may make sense to ask the WeMod folks in their discord. Closing for now, feel free to re-open the issue if you feel like it's an issue addressable by `wemod-launcher`
