### ISSUE TITLE
Include dependency on tkinter

### ISSUE THREAD

**Issue by SethFalco** [DaniAsh551/wemod-launcher#29]
Thanks for creating the repo! While setting this up on a friend's device, I found that a dependency was missing from the setup instructions.

Before I was able to proceed, I had to install tkinter manually on Fedora. I ran `sudo dnf install python3-tkinter`, which then enabled me to finish the installation.

---

Note: I'm able to submit a PR to include this step later, but I don't have the laptop on hand for now. Once I have it again, I will attempt the end-to-end steps again so I know the best place to put it, and may test on other distributions. I suspect we'd need to install the respective tkinter package for whatever distribution.

**Comment by DaniAsh551** [comment]
hey @SethFalco, thanks for raising this issue. Since the dependency you mentioned is a system-wide dependency, we probably would have a hard time enforcing it. Not to mention that on read-only distros and flatpak versions of steam it might not be achievable either

On the otherhand, we could enforce where we can and inform where we cannot?
If you append the instructions to the guide, I would be happy to merge.

**Comment by marvin1099** [comment]
The info that TK is required is now included in the readme.
