### ISSUE TITLE
How do i fix this

### ISSUE THREAD

**Issue by TheCorruptCat** [DaniAsh551/wemod-launcher#37]
ERROR: ld.so: object '/home/carter/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

/bin/sh: line 1: /home/carter/wemod-launcher/wemod: No such file or directory

**Comment by marvin1099** [comment]
make sure you have the wemod laucher folder at the location `/home/carter/wemod-launcher`
and make shure the file `/home/carter/wemod-launcher/wemod` exists
if the file is missing redownload by deleting the wemod folder and runnig `git clone https://github.com/DaniAsh551/wemod-launcher.git` in your home.

also make sure you have python installed.
Than it probably works.
If not you can also try the command:
`WEMOD_LOG=/home/deck/wemod-launcher/wemod.log python /home/carter/wemod-launcher/wemod %command%`
instead of 
WEMOD_LOG=/home/deck/wemod-launcher/wemod.log /home/carter/wemod-launcher/wemod %command%

This assumes that your Linux account username-folder is carter

**Comment by DaniAsh551** [comment]
@marvin1099 thanks for the input
@TheCorruptCat feel free to reopen if you still face the issue
