### ISSUE TITLE
Fix images in readme

### ISSUE THREAD

**Issue by marvin1099** [DaniAsh551/wemod-launcher#38]
It seems the readme has dead images,
I think it would be nice if all the images wold work once more.
For that it might make scene to have the images in the repo in a image folder.
I have seen that you have used discord links
and it seems they might be destroyed after some time.
Below i have a image of the readme ringht now, 
there a few lines that say image in blue,
these are the dead images
<img src="https://github.com/DaniAsh551/wemod-launcher/assets/40715852/9f783b20-128f-419f-9b04-c8414b9d4a55" width=60%>

**Comment by DaniAsh551** [comment]
Yeah, I have noticed that, at the beginning, @JohnHamwi put the guide together on the official WeMod Discord, and I copied it over to here, and linked the images directly to discord channel.

The channel has since then, been deleted and their plans about this are still unknown to me.

We would either need to make the images again or, if @JohnHamwi has them, we could upload those again.

**Comment by marvin1099** [comment]
Hm well, if @JohnHamwi has them we can add them, but right now we don't.
So if you or @JohnHamwi still know what these images are, remaking them might be doable.
But since we don't know these i think for now lets remove the images that are broken.
The ones that still work, we should add to the readme directly so they don't break.
Of course if we find the images or have recreated them we can add them back but for now,
these broken images just aren't nice, so lets remove them. 

What do you think?

**Comment by marvin1099** [comment]
I have reworked the readme [In merge 41](https://github.com/DaniAsh551/wemod-launcher/pull/41) I think its nicer now, wee can always roll back anyway.
